<a href="https://colab.research.google.com/github/daniellekarlas/MLSENAC_Danielle/blob/main/atividadecasaAula8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Arange

In [2]:
arr1 = np.arange(10)

In [3]:
arr2=np.arange(10,20)

In [4]:
arr3=np.arange(10,20,2)

In [5]:
arr4=np.arange(10,20,1.4)

array com linspace

In [6]:
arr5=np.linspace(10,20,11)


In [7]:
arr6=np.linspace(10,20,101)

In [8]:
arr7=np.linspace(0, np.pi, 100)

Numpy: Matrizes


In [9]:
#criando a primeira matriz
minhaMatriz=np.array([[1,2,3],
                      [4,5,6]])

In [10]:
##pode ser escrita assim 
minhaMatriz=np.array([[1,2,3],[4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
##podemos criar uma matriz a partir de uma lista
minhaLista=[[13,81,22], [0,34,59], [21,48,94]]

In [12]:
##agora usaremos np.matriz
minhaMatriz=np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [13]:
##np.zeros: pode formar vetores e matrizes
#vetor
x=np.zeros(3)
x

array([0., 0., 0.])

In [14]:
#matriz
x=np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
##np.zeros: pode formar vetores e matrizes
#outra forma sem armazenar em variáveis
#vetor
print(np.zeros(3))

[0. 0. 0.]


In [16]:
#matriz
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
#np.ones:
x=np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#igualmente é possível para apenas um vetor:
y=np.ones(5)
y

array([1., 1., 1., 1., 1.])

DESAFIO: como obter uma matriz 4x4 apenas com números 8?

In [19]:
minhaLista=[[[8]*4]]
minhaMatriz2=np.array(minhaLista*4)
minhaMatriz2

array([[[8, 8, 8, 8]],

       [[8, 8, 8, 8]],

       [[8, 8, 8, 8]],

       [[8, 8, 8, 8]]])

In [20]:
##np.diag para formar matrizes:
#os valores passados como parâmero formam uma diagonal
z=np.diag(np.array([1,2,3,4,5,6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [21]:
#np.eye para formar matrizes:
y=np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
#agora determinamos o tipo int:
y=np.eye(5, dtype=int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
#verificando o shape(forma) de duas maneiras:
np.shape(minhaMatriz)

(3, 3)

In [24]:
minhaMatriz.shape

(3, 3)

In [25]:
#verificando o tipo de matriz:
type(minhaMatriz)

numpy.matrix

In [26]:
#verificando o tipo de dados da matriz
minhaMatriz.dtype

dtype('int64')

In [27]:
#selecionando elementos de uma matriz
minhaMatriz[2, 1] 

48

In [28]:
#selecionando a primeira linha da matriz
print(minhaMatriz[0,:])

[[13 81 22]]


In [29]:
#selecionando a terceira coluna da matriz
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [30]:
#alterando um elemento da matriz
minhaMatriz[1,0]=100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [31]:
meuArray=minhaMatriz

operações básicas

In [32]:
#obtendo a soma dos valores do array
np.sum(meuArray)

472

In [33]:
#obtendo o produto
np.prod(meuArray)

440321981299200

In [34]:
#obtendo a soma acumulada
np.cumsum(meuArray)

matrix([[ 13,  94, 116, 216, 250, 309, 330, 378, 472]])

In [35]:
#obtendo o valor mínimo do array
meuArray.min()

13

In [36]:
#obtendo o valor máximo
meuArray.max()

100

In [37]:
#obtendo a média dos valores do array
np.mean(meuArray)

52.44444444444444

In [38]:
#obtendo a mediana
np.median(meuArray)

matrix([[ 21.,  13.,  22.,  34.,  48.,  59.,  81.,  94., 100.]])

In [39]:
#obtendo a variância dos valores
np.var(meuArray)

964.246913580247

In [40]:
#obtendo o desvio padrão dos valores
np.std(meuArray)

31.052325413409008

Desafio
Criar um array unidimensional usando arange com 20 elementos;
● “Varrer” o array para obter os pares;
● “Varrer” o array para obter os ímpares;
● Obter a média, a soma, o produto, a variância e o desvio padrão
do array.
● Saber se os valores são maiores que 5;
● Obter os valores maiores que 5.

In [92]:
arr8=np.arange(20)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
par=np.where(arr8 %2==0)
print(par)


(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)


In [94]:
impar=np.where(arr8%2==1)
print(impar)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)


Camilla, abaixo eu vou colocar um outro array que eu tinha gerado, e estava dando erro com a função np.where, quando eu pedia os pares, ele retornava o ímpar e vice-versa.

In [98]:
arrayteste=np.arange(1, 21)

par=np.where(arrayteste %2==0)
print(par)

impar=np.where(arrayteste %2==1)
print(impar)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)


In [99]:
np.mean(arr8)

9.5

In [100]:
np.sum(arr8)

190

In [101]:
np.prod(arr8)

0

In [102]:
np.var(arr8)

33.25

In [103]:
np.std(arr8)

5.766281297335398

In [113]:
for num in arr8:
  if num >5:
    print("True")
  else:
    print("False")

False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [105]:
arr8>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [111]:
for num in arr8:
  if num>5:
    print(num)


6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [112]:
arr8[arr8>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])