<a href="https://colab.research.google.com/github/daniellekarlas/MLSENAC_Danielle/blob/main/Aula6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

In [2]:
minhaLista=[0,1,2,3,4,5,6,7,8]

In [14]:
meuArray=np.array(minhaLista) #transformar lista em um array numpy
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [11]:
minhaLista=list(range(9)) #uma forma mais simples de criarmos essa lista
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
array1=np.array(range(9)) #transgormando a lista em um array numpy
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array2=np.arange(9) #arange: fazendo as etapas anteriores numa única sintaxe
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
#start, stop, step
array3=np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [17]:
#arrendondando os valores obtidos
novoArray=np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [23]:
array3=np.arange(0,10,0.5, dtype=int) #também podemos forçar o tipo de elementos
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
array4=np.arange(12) #podemos pré determinar o tipo dos elementos

In [24]:
array4=np.arange(12.) #no array acima teremos os números inteiros, mas posso deixar meu array previamente preparadp para trabalhar com tipos float;
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [27]:
type(array4) #verificando o tipo do objeto

numpy.ndarray

In [29]:
array4.dtype #verifica o tipo dos elementos do array

dtype('float64')

In [35]:
print(array4.dtype) #verifica o tipo dos elementos do array

float64


In [36]:
vetor1=np.array([0,1,2,3,4]) #criar um array digitando os valores
print(vetor1)

[0 1 2 3 4]


In [37]:
vetor1[3] #selecionando um elemento específico

3

In [38]:
vetor1[0:2] #selecionando um intervalo específico

array([0, 1])

In [39]:
print(vetor1[0:2]) #selecionando um intervalo específico

[0 1]


In [45]:
s=np.array(["Python", "Profissional", "Java", "Água"]) #todos da mesma forma
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [46]:
s=np.array(["Python", 1464321315, "Profissional", "Java", "Água"]) #com tipos diferentes de dados
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [47]:
#alterando um elemento do Array
vetor1[2]=10
vetor1

array([45,  1, 10,  3,  4])

In [43]:
vetor1[0]="Novo elemento" #ele não aceita string 

ValueError: ignored

In [49]:
vetor1[0]=45.6 #ele aadicionou o valor inteiro
vetor1

array([45,  1, 10,  3,  4])